pyhkweb/pyhkweblib/pyhk_blueprint.py
import flask
import logging
import ast
import datetime
import json
import os
import urllib.request, urllib.parse, urllib.error
import requests
import time
import platform
import psutil
import numpy as np

from collections import OrderedDict

from pyhkdremote.data_loader import pyhkd_get_filename, pyhkd_get_latest, pyhkd_get_config_dir, pyhkd_get_names
from pyhkdremote.settings import DATA_LOG_FOLDER
from pyhkdremote.control import pyhkd_set
from pyhkfridgeremote.data_loader import pyhkfridge_get_state, pyhkfridge_get_log_filename, pyhkfridge_get_script_dir
from pyhkfridgeremote.control import pyhkfridge_get_active_ports
import pyhkfridgeremote.control
from livecfg.livecfg import LiveCfg
from .cache import cache
import units.units as units
import gitinfo

# Returns the correct function to convert between two units ("K", "C", etc).
# Returns None on failure
def get_unit_func(start, finish):
	funcname = str(start).replace('/','p') + '2' + str(finish).replace('/','p')
	try:
		func = getattr(units, funcname)
		return func
	except AttributeError:
		return None

pyhkpage = flask.Blueprint('pyhkpage', __name__,template_folder='templates')

# Check if a page name is a valid page of the given type.  If so, return 
# it.  If not, return the first such valid page.  If no valid page
# exists, return None.
def find_page_name(cur_page_id, page_config, page_type):

	if cur_page_id is not None:
		if cur_page_id in list(page_config.keys()):
			if page_config[cur_page_id]['page_type'] == page_type:
				return cur_page_id
	
	# We have a bad name, so find the first (in order) valid page name	
	for k in flask.current_app.config['page_ids']:
		if page_config[k]['page_type'] == page_type:
			return k
			
	# No valid pages exist
	return None

# Inject global variables used by all templates
@pyhkpage.context_processor
def inject_settings():
	settings = {
		'page_ids': flask.current_app.config['page_ids'], 
		'maintenance_mode': flask.current_app.config['internal_settings'].get("maintenance_mode", False),
		'site_name': flask.current_app.config['internal_settings'].get("site_name", None),
		'unit_symbol_default': units.unit_symbol_default,
		'unit_id_short': units.unit_id_short
	}
	return settings
    
@pyhkpage.route("/control/pyhkd/", methods=["POST"])
def request_pyhkd_set():
	# pyhkd checks its inputs carefully, no sense repeating that here
	command = flask.request.form.get('command')
	name = flask.request.form.get('name')
	value = flask.request.form.get('value')
	pyhkd_set(command, name, value, retry=False)
	return "Request Sent"

# None for target_date or num_days means to use the current local session value
@pyhkpage.route("/")
@pyhkpage.route("/plot")
@pyhkpage.route("/plot/<cur_page_id>")
@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>")
@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>/")
def plot(cur_page_id=None, target_date=None, num_days=None, plot_mode=0, plot_dt=None):
	
	page_config = flask.current_app.config['page_config']
	cur_page_id = find_page_name(cur_page_id, page_config, page_type='plot')
	
	if cur_page_id is None:
		return "No plot pages exist!", 400
	
	page_title = page_config.get(cur_page_id,{}).get('page_title','Plot')
	plots = page_config[cur_page_id].get("plots", [])
	num_plots = len(plots)
	
	# Build the axis labels
	labels = ['']*num_plots
	unit_labels = ['']*num_plots
	for i in range(num_plots):
		labels[i] = units.unit_id_short.get(plots[i]['subfolder_label'], 'Unknown')
		dflt = units.unit_symbol_default.get(plots[i]['subfolder_label'], '')
		unit_labels[i] = plots[i].get("units", dflt)
		if unit_labels[i]:
			labels[i] += ' [' + unit_labels[i] + ']'
		else:
			unit_labels[i] = 'none' # Value for the url, not shown
		unit_labels[i] = unit_labels[i].replace('/','p')
	
	return flask.render_template("plot.html",   cur_page_id = cur_page_id, 
												page_config = page_config,
												page_title = page_title,
												num_plots = num_plots,
												axis_label = labels,
												target_date = target_date,
												plot_mode = plot_mode,
												plot_dt = plot_dt,
												num_days = num_days,
												unit_labels = unit_labels)

@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>/compare")
@pyhkpage.route("/plot/<cur_page_id>/<int:num_days>/<target_date>/compare/<signed_int:plot_dt>sec")
def plot_compare(cur_page_id, target_date, num_days, plot_dt=None, plot_mode=1):
	return plot(cur_page_id=cur_page_id, target_date=target_date, num_days=num_days, plot_mode=plot_mode, plot_dt=plot_dt)
																				
valid_generic_pages = ["panel", "adr", "tables", "heaters", "pt", "gpio", "export", "ls336"]
@pyhkpage.route("/<page_type>")
@pyhkpage.route("/<page_type>/<cur_page_id>")
def generic_page(page_type, cur_page_id=None):
	if page_type not in valid_generic_pages:
		return "Invalid page type!", 400
	page_config = flask.current_app.config['page_config']
	cur_page_id = find_page_name(cur_page_id, page_config, page_type=page_type)
	if cur_page_id is None:
		return "No " + page_type + " pages exist!", 400
	page_title = page_config.get(cur_page_id,{}).get('page_title', page_type.capitalize())
	return flask.render_template(page_type + ".html",cur_page_id = cur_page_id, 
												page_config = page_config,
												page_title = page_title,
												axis_labels = units.unit_labels_full)
							
# value_names should be given as repr(list) for passing to ast.literal_eval.
@pyhkpage.route("/data/current/<subfolder_label>/<units_name>/<value_names>.json")
@pyhkpage.route("/data/current/<subfolder_label>/default/<value_names>.json")
def get_data_current(subfolder_label, value_names, units_name='default'):

	# Try to load the unit conversion function
	dflt = units.unit_symbol_default.get(subfolder_label)
	conv_func = None
	#logging.debug("Requested units: " + str(units_name) + " (" + str(subfolder_label) + ")")
	if units_name not in ['default', dflt]:
		conv_func = get_unit_func(dflt, units_name)
		logging.debug("Attempting to load unit conversion from " + str(dflt) + " to " + str(units_name) + ". Found: " + str(conv_func))
	
	# Data comes in as repr(actual_list), so we need to convert it.
	# ast.literal_eval is safe with untrusted strings.
	try:
		value_names = ast.literal_eval(value_names)
	except:
		logging.error("Bad value names passed to get_data_current: " + str(value_names))
		return "", 400
		
	results = OrderedDict()
	for n in value_names:
		ts, v = pyhkd_get_latest(DATA_LOG_FOLDER, subfolder_label, n, return_as_datetime = False)
		if ts is not None:
			
			if v is not None:
				
				if conv_func is not None:
					v = conv_func(v)
				
				# NaN isn't allowed in strict json, was causing some issues.
				# None converts to null and is allowed.
				if not np.isfinite(v):
					v = None
				
			results[n] = (int(1000*ts), v)
			
	return json.dumps(results)
		
	
# Load a day's worth of archived data for a list of sensors, downsampling
# each sensor as needed.  target_date is a string of the form YYYYMMDD.
# value_names should be given as repr(list) for passing to ast.literal_eval.
# max_points_each is max reported points for all days for one value_name.
# Currently each day for each value_name will be downsampled to
# max_points_each/num_days points, but this may change in the future.
PLOTMODE_NORMAL = 0
PLOTMODE_LIVECOMPARE = 1
PLOTMODE_FASTDATA = 2
VALID_PLOTMODES = [PLOTMODE_NORMAL, PLOTMODE_LIVECOMPARE, PLOTMODE_FASTDATA]

MAX_TOTAL_POINTS = 30000
PLOT_URL = "/data/archive/<target_date>/mode<int:plot_mode>/<signed_int:plot_dt>sec/<int:num_days>/<subfolder_label>/<units_name>/<value_names>.csv"
@pyhkpage.route(PLOT_URL)
@pyhkpage.route(PLOT_URL.replace("<target_date>", "today"))
def get_data_archive(subfolder_label, value_names, units_name='default', target_date = None, num_days = 1, plot_mode = PLOTMODE_NORMAL, 
	plot_dt = 0, max_points_each = 5000):
	
	logging.debug("Data archive requested")
	
	if target_date is None:
		target_date = datetime.date.today()
	else:
		try:
			target_date = datetime.datetime.strptime(target_date, '%Y%m%d').date()
		except ValueError:
			logging.error("Bad target date passed to get_data_archive: " + str(target_date))
			return "", 400

	if plot_mode not in VALID_PLOTMODES:
		plot_mode = PLOTMODE_NORMAL
		
	try:
		num_days = int(num_days)
	except:
		logging.error("Bad day count passed to get_data_archive: " + str(num_days))
		return "", 400
	
	# Restrict the date range
	num_days = np.clip(num_days, 1, 14)

	# Data comes in as repr(actual_list), so we need to convert it.
	# ast.literal_eval is safe with untrusted strings.
	try:
		value_names = ast.literal_eval(value_names) 
		if not isinstance(value_names, list):
			value_names = [value_names]
	except:
		logging.error("Bad value names passed to get_data_archive: " + str(value_names))
		return "", 400
		
	# Set harsher point count limits for very busy plots
	max_points_each = min(max_points_each, int(MAX_TOTAL_POINTS / len(value_names)))
	
	# Set harsher point count limits for very busy plots
	max_points_each = min(max_points_each, int(MAX_TOTAL_POINTS / len(value_names)))
	
	# We can't use the cached function for today or the future, both
	# to prevent incomplete data loads and to keep it from caching
	# for a day that isn't complete. 
	if target_date < datetime.date.today() and plot_mode == PLOTMODE_NORMAL:
		return get_data_archive_helper(subfolder_label, value_names, 
					target_date, num_days, max_points_each, units_name, 
					plot_mode=0, plot_dt=0)
	else:
		logging.debug("Skipping data archive cache, date isn't in the past")
		return get_data_archive_helper.uncached(subfolder_label, value_names, 
					target_date, num_days, max_points_each, units_name, 
					plot_mode, plot_dt)


# Cached helper function doing the data loading/processing for
# get_data_archive.  Assumed inputs are already verified and transformed 
# to their proper types - value_names is a list, target_date is a 
# datetime.date, num_days is a postive integer.

pyhkweb/templates/adr.html
{% extends "livedata-base-page.html" %}

% set name_prefix = page_config[cur_page_id]['name_prefix']

{% block header %}

	{{ super() }}
	
	<script type="text/javascript">
		
		// Custom handler for this one value
		STATE_LABELS = ['Invalid', 'Ramping', 'Holding', 'Paused', 'Manual Up', 'Manual Down', 'Zeroing', 'Quench Detected', 'Heating PSwitch', 'At Zero']
		function new_data_custom_adrstate (data)
		{
			console.log("New data received: " + JSON.stringify(data));
			for (tname in data)
			{
				val =  data[tname][1];
				$("[id='val_adr_state']").html(STATE_LABELS[val]);
			}
		}
	
		function update_data() 
		{
			console.log("Requesting new data");
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='state', value_names=[name_prefix + ' State']) }}", new_data_custom_adrstate);
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='current', value_names=[name_prefix + ' Programmed I']) }}", new_data_func['current']);
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='currentramp', value_names=[name_prefix + ' Programmed Ramp']) }}", new_data_func['currentramp']);
			
		}	
		
		$( document ).ready(function() 
		{
			update_data();
			var update_timer = setInterval(update_data, 2000);
		});
		
	</script>
		
{% endblock %}

{% block content %}

	<p>
		
		<table class='prettytable' border="1">
			
			<tr>
				<th>Name</th>
				<th>Value</th>
				<th>Change</th>
			</tr>
			
			<tr>
				<td>State</td>
				<td><div id="val_adr_state"></div></td>
				<td>
					<select id="set_state">
					% set MODE_LABELS = ['Pause', 'Ramp', 'Zero']
					% for j in range(MODE_LABELS|length)
						<option value={{j}}>{{MODE_LABELS[j]}}</option>
					% endfor
					</select>
					<button onclick="request_set_s('set_state', '{{ name_prefix|e }}')">Set</button>
				</td>
			</tr>
			
			<tr>
				<td>Target Current</td>
				% set sensor_name = name_prefix + " Programmed I"
				<td><div id="val_current_{{ sensor_name|urlencode }}"></div></td>
				<td>
					<input type="number" id="set_mag_i" style="width:80px;"></input>
					<button onclick="request_set_i('set_mag_i', '{{ name_prefix|e }}')">Set A</button>
				</td>
			</tr>
			
			<tr>
				<td>Target Ramp</td>
				% set sensor_name = name_prefix + " Programmed Ramp"
				<td><div id="val_currentramp_{{ sensor_name|urlencode }}"></div></td>
				<td>
					<input type="number" id="set_mag_ir" style="width:80px;"></input>
					<button onclick="request_set_ir('set_mag_ir', '{{ name_prefix|e }}')">Set A/s</button>
				</td>
			</tr>
			
		</table>			
		
	</p>
	

{% endblock %}

pyhkweb/templates/base-page.html
<!doctype html>
<html>

<head>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	
	{% block header %}{% endblock %}
	
	<title>{{site_name|e if site_name else "PyHK"}} - {{page_title}}</title>
	
	<style>
		body {
			margin: 0;
			font-family: Arial, Helvetica, sans-serif;
		}
		
		.mainnavpanel ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			width: 200px;
			background-color: #616265;
			position: fixed;
			z-index: 100000;
			height: 100%;
			overflow: auto;
			
		}

		.mainnavpanel li a, .mainnavpanel li h3, .mainnavpanel li h4 {
			display: block;
			color: #000;
			padding: 7px 16px;
			text-decoration: none;
			color: white;
		}


		.mainnavpanel li a.active {
			background-color: #FF6E1E;
			color: white;
		}

		.mainnavpanel li a:hover:not(.active) {
			background-color: #76777B;
			color: white;
		}
		
		/* Highlight every other */
		.prettytable:not(.prettytable-quad) tr:nth-child(odd) {
			background-color: #E0E0E0
		}
		
		/* Highlight groups of four */
		.prettytable-quad tr:nth-child(8n+6) {
		  background: #E0E0E0;
		}
		.prettytable-quad tr:nth-child(8n+7) {
		  background: #E0E0E0;
		}
		.prettytable-quad tr:nth-child(8n+8) {
		  background: #E0E0E0;
		}
		.prettytable-quad tr:nth-child(8n+9) {
		  background: #E0E0E0;
		}
				
		.prettytable td {
			padding: 6px;
			text-align: center;
		}
		.prettytable th {
			padding: 6px;
			text-align: center;
			font-weight: bold;
			background-color: #FF6E1E;
			color: white;
		}
		.prettytable {
			font-size: 14px;
		}
		table {
			border-collapse: collapse;
			border-color: black;
		}
		.column {
			float: left;
			padding: 10px;
		}
		.clearfix::after {
			content: "";
			clear: both;
			display: table;
		}		
		
		@keyframes updatepinganim 
		{
			0% 
			{
				text-shadow: 0 0 1px black;
			}
			100% 
			{
				text-shadow: none;
			}
		}
		
		.newvalue 
		{
			animation-duration: 2s;
			animation-timing-function: ease-in;
			animation-delay: 0s;
			animation-iteration-count: 1;
			animation-name: updatepinganim;
		}
		
		/* jquery UI theme */
		
		.ui-datepicker {
			font-size: 11px;
		}
		
		.ui-state-active,
		.ui-widget-content .ui-state-active,
		.ui-widget-header .ui-state-active,
		a.ui-button:active,
		.ui-button:active,
		.ui-button.ui-state-active:hover {
			border: 1px solid #616265;
			background: #FF6E1E;
			font-weight: normal;
			color: #ffffff;
		}
		.ui-state-highlight,
		.ui-widget-content .ui-state-highlight,
		.ui-widget-header .ui-state-highlight {
			border: 1px solid #FF6E1E;
			background: #f6f6f6;
			color: #454545;
		}
		
		.ui-corner-all,
		.ui-corner-top,
		.ui-corner-left,
		.ui-corner-tl {
			border-top-left-radius: 0;
		}
		.ui-corner-all,
		.ui-corner-top,
		.ui-corner-right,
		.ui-corner-tr {
			border-top-right-radius: 0;
		}
		.ui-corner-all,
		.ui-corner-bottom,
		.ui-corner-left,
		.ui-corner-bl {
			border-bottom-left-radius: 0;
		}
		.ui-corner-all,
		.ui-corner-bottom,
		.ui-corner-right,
		.ui-corner-br {
			border-bottom-right-radius: 0;
		}
		
		/* Hide the arrows for number fields */
		input[type='number'] {
			-moz-appearance:textfield;
		}
		input[type=number]::-webkit-inner-spin-button,
		input[type=number]::-webkit-outer-spin-button {
			-webkit-appearance: none;
			margin: 0;
		}
	</style>
	
	<script type="text/javascript">
		
		$( document ).ready(function() 
		{
			const url_params = new URLSearchParams(window.location.search);
			
			// Hide the main navigation panel and page title
			if (url_params.get('hidenav') == 'true')
			{
				document.getElementById("mainnavpanel").style["display"] = "none";
				document.getElementById("pagetitleheading").style["display"] = "none";
				document.getElementById("mainpagecontents").style["margin-left"] = "0px";
				document.getElementById("mainpagecontents").style["padding"] = "0px";
				
			}
		});
		
	</script>
	
</head>

<body>
	% if maintenance_mode
		<div style="background-color: yellow; border: 2px solid red; padding: 2px; font-weight: bold; text-align: center;">
		The website is currently in maintenance mode.  You may continue to use it, but you may notice disruptions as code is updated.
		</div>
	% endif

	<div class="mainnavpanel" id="mainnavpanel">
	
		<ul>
			<li style="text-align: center; margin: 18px 4px">
				% if site_name
					<h3 style="font-size: 24px; font-weight:bold; padding: 0px 0px; margin: 4px 16px">{{site_name|e}}</h3>
					<h4 style="font-size: 14px; font-weight:normal; padding: 0px 0px; margin: 4px 16px">PyHK Web Viewer</h4>
				% else
					<h3 style="font-size: 18px; font-weight:bold; padding: 0px 0px; margin: 4px 16px">PyHK Web Viewer</h3>
				% endif
			</li>
			% for dn in page_ids
				% set active_str = ""
				% if dn == cur_page_id
					% set active_str = "active "
				% endif
				
				% with pt = page_config[dn]["page_type"]
				
					<li><a class="{{active_str}}pagelink_{{pt}}" id="pagelink_{{dn}}" href=			

					% if pt in ["plot", "ls370", "hkmb"]
						"{{ url_for('pyhkpage.' + pt, cur_page_id=dn) }}"
					% elif pt in ["fridge", "camera", "about"]
						"{{ url_for('pyhkpage.' + pt) }}"
					% elif pt not in ["internal_settings"]
						"{{ url_for('pyhkpage.generic_page', page_type=pt, cur_page_id=dn) }}"
					% endif
				% endwith
				
				>{{page_config[dn]["page_title"]}}</a></li>
				
			% endfor
		</ul>
		
	</div>

	<div style="margin-left:210px;padding:1px 16px;" id="mainpagecontents">
		<h2 id="pagetitleheading">{{page_title}}{% block titlesuffix %}{% endblock %}</h2>
		{% block content %}{% endblock %}
	</div>
	
</body>
	
</html>

pyhkweb/templates/gpio.html
{% extends "livedata-base-page.html" %}

% set name_prefix = page_config[cur_page_id]['name_prefix']

{% block header %}

	{{ super() }}
	
	<script type="text/javascript">
	
		function update_data() 
		{
			console.log("Requesting new data");
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='state', value_names=page_config[cur_page_id]['names']) }}", new_data_func['state']);
		}		
		
		$( document ).ready(function() 
		{
			update_data();
			var update_timer = setInterval(update_data, 2000);
		});
		
	</script>
		
{% endblock %}

{% block content %}

	<p>
		
		<table class='prettytable' border="1">
			
			<tr>
				<th>Name</th>
				<th>Value</th>
				<th>Change</th>
			</tr>
			
			% for n in page_config[cur_page_id]['names']
				<tr>
					<td>{{ n|e }}</td>
					<td><div id="val_state_{{ n|urlencode }}"></div></td>
					<td>
						<button onclick="request_set_val_s('{{ n|e }}', 0)">0</button>
						<button onclick="request_set_val_s('{{ n|e }}', 1)">1</button>
					</td>
				</tr>
			% endfor
			
		</table>			
		
	</p>
	

{% endblock %}

pyhkweb/templates/heaters.html
{% extends "livedata-base-page.html" %}

% set use_power = page_config[cur_page_id]['use_power']
% set use_temperature = page_config[cur_page_id]['use_temperature']

{% block header %}

	{{ super() }}
	
	<script type="text/javascript">
		
		unit_lims['voltage'] = [-3,0];
		unit_lims['current'] = [-3,0];
		unit_lims['power'] = [-6,0];
	
		function update_data() 
		{
			console.log("Requesting new data");
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='voltage', value_names=page_config[cur_page_id]['names']) }}", new_data_func['voltage']);
			% if use_power
				$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='power', value_names=page_config[cur_page_id]['names']) }}", new_data_func['power']);
				$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='current', value_names=page_config[cur_page_id]['names']) }}", new_data_func['current']);
			% endif
			% if use_temperature
				$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='temperature', value_names=page_config[cur_page_id]['names']) }}", new_data_func['temperature']);
			% endif
		}	
		
		$( document ).ready(function() 
		{
			update_data();
			var update_timer = setInterval(update_data, 2000);
		});
		
	</script>
		
{% endblock %}

{% block content %}

	<p>
		
		<table class='prettytable' border="1">
			
			<tr>
				<th>Name</th>
				<th>Voltage</br>(Requested)</th>
				% if use_temperature
					<th>Temperature</br>(Requested)</th>
				% endif
				% if use_power
					<th>Current</br>(Measured)</th>
					<th>Power</br>(I<sup>2</sup> * R<sub>heater</sub>)</th>
				% endif
				<th>Change</th>
			</tr>
			
			% for n in page_config[cur_page_id]['names']
				<tr>
					<td>{{ n|e }}</td>
					<td><div id="val_voltage_{{ n|urlencode }}" style="text-align:center"></div></td>
					% if use_temperature
						<td><div id="val_temperature_{{ n|urlencode }}" style="text-align:center"></div></td>
					% endif
					% if use_power
						<td><div id="val_current_{{ n|urlencode }}" style="text-align:center"></div></td>
						<td><div id="val_power_{{ n|urlencode }}" style="text-align:center"></div></td>
					% endif
					<td>
						<input type="number" id="toset_{{ n|urlencode }}" style="width:80px;"></input>
						<button onclick="request_set_v('toset_{{ n|e }}', '{{ n|e }}')">Set V</button>
						% if use_temperature
							<button onclick="request_set_t('toset_{{ n|e }}','{{ n|e }}')">Set K</button>
						% endif
						% if use_power
							<button onclick="request_set_p('toset_{{ n|e }}','{{ n|e }}')">Set mW</button>
						% endif
						<button onclick="request_set_v_zero('toset_{{ n|e }}','{{ n|e }}')">Zero</button>
					</td>
				</tr>
			% endfor
			
		</table>			
		
	</p>
	

{% endblock %}

pyhkweb/templates/pt.html
{% extends "livedata-base-page.html" %}

% set name_prefix = page_config[cur_page_id]['name_prefix']

{% block header %}

	{{ super() }}
	
	<script type="text/javascript">
		
		function request_set_pt()
		{
		
			var val = $("[id='set_state']").val();
			var verify = $("[id='txt_verify']").val();
			
			if (val == 1)
			{
				if (verify != "I want to turn the PT on")
				{
					window.alert("Bad verification string.  Type exactly as written, no quotes.");
					return;
				}
			}
			else if (val == 2)
			{
				if (verify != "I want to turn the PT off")
				{
					window.alert("Bad verification string.  Type exactly as written, no quotes.");
					return;
				}
			}
			else
			{
				return;
			}
			
			request_set_s('set_state', '{{ name_prefix|e }} On State')
			window.alert("PT state change requested successfully");
		}
		
		
		// Special handling for the PT state value
		STATE_LABELS = ['Off', 'On'];
		function new_data_custom_ptstate(data)
		{
			console.log("New PT state data received: " + JSON.stringify(data));
			for (tname in data)
			{
				val =  data[tname][1];
				$("[id='val_pt_status']").html(STATE_LABELS[val]);
			}
		}
	
		function update_data() 
		{
			console.log("Requesting new data");
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='state', value_names=[name_prefix + ' Status']) }}", new_data_custom_ptstate);
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='state', value_names=[name_prefix + ' Error']) }}", new_data_func['state']);
			$.getJSON("{{ url_for('pyhkpage.get_data_current', subfolder_label='state', value_names=[name_prefix + ' Compressor Minutes']) }}", new_data_func['state']);
		}	
		
		$( document ).ready(function() 
		{
			update_data();
			var update_timer = setInterval(update_data, 2000);
		});
		
	</script>
		
{% endblock %}

{% block content %}

	<p>
		
		<table class='prettytable' border="1">
			
			<tr>
				<th>Name</th>
				<th>Value</th>
			</tr>
			
			<tr>
				<td>Status</td>
				<td><div id="val_pt_status"></div></td>
			</tr>
			
			<tr>
				<td>Error</td>
				% set sensor_name = name_prefix + " Error"
				<td><div id="val_state_{{ sensor_name|urlencode }}"></div></td>
			</tr>
			
			<tr>
				<td>Compressor Minutes</td>
				% set sensor_name = name_prefix + " Compressor Minutes"
				<td><div id="val_state_{{ sensor_name|urlencode }}"></div></td>
			</tr>
			
		</table>			
		
	</p>
	
	<p>
		<h4>Turn PT On/Off</h4>
	
		To help prevent accidental clicks, enter one of the following text strings into the textbox exactly as written (no quotes) for changes to take effect:<br>
		<i>"I want to turn the PT on"</i><br>
		<i>"I want to turn the PT off"</i><br>
		<br>
		
		<input type="text" id="txt_verify" value="" style="width:300px;">
		
		<br>
		<br>
		
		<select id="set_state">
		% set MODE_LABELS = ['No Change', 'On', 'Off']
		% for j in range(MODE_LABELS|length)
			<option value={{j}}>{{MODE_LABELS[j]}}</option>
		% endfor
		</select>
		<button onclick="request_set_pt()">Set</button>
	
	</p>
	

{% endblock %}

pyhkweb/templates/simple-code.html
<!doctype html>
<html>

<head>
	
	<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
	
	<title>{{cur_page_name}}</title>
	
	<style>
		pre
		{
			-moz-tab-size: 4;
			-o-tab-size:   4;
			tab-size:      4;
		}
	</style>
	
</head>

<body>
	
	<pre class="prettyprint">{{code_text}}</pre>
	
</body>
	
</html>